# roles/desktop/tasks/config_root.yml
---

# *** web-greeter ***

# Instalar dependencias de web-greeter
- name: Instalar dependencias de web-greeter
  apt:
    name:
      - acpid
      - accountsservice
    state: present

# Asegurar que el servicio acpid esté activo
- name: Asegurar que el servicio acpid esté activo
  service:
    name: acpid
    enabled: yes
    state: started

# Verificar que el archivo web-greeter.deb existe
- name: Verificar que el archivo web-greeter.deb existe
  stat:
    path: "{{ web_greeter_deb_path }}"
  register: web_greeter_deb_path_dir_stat

# Mostrar mensaje si el archivo web-greeter.de no existe
- name: Fallar si el archivo web-greeter.deb no existe
  fail:
    msg: "El archivo {{ web_greeter_deb_path }} no existe. No se puede instalar web-greeter."
  when: not web_greeter_deb_path_dir_stat.stat.exists

# Recolectar facts de paquetes instalados
- name: Recolectar facts de paquetes instalados
  package_facts:
    manager: apt

# Instalar web-greeter .deb package
- name: Instalar web-greeter .deb package
  apt:
    deb: "{{ web_greeter_deb_path }}"
  when: >
    "'web-greeter' not in ansible_facts.packages" and
    web_greeter_deb_path_dir_stat.stat.exists

