---
- name: Establecer permisos de directorio home
  file:
    path: "~"
    mode: '0710'

- name: Crear directorio ~/.mpd/playlists
  file:
    path: "~/.mpd/playlists"
    state: directory
    mode: '0777'

- name: Copiar configuración de MPD para usuario
  copy:
    src: "mpd.conf"
    dest: "~/.mpd/mpd.conf"
    mode: '0644'

- name: Habilitar servicio mpd para alex (systemd user)
  systemd:
    name: mpd.service
    enabled: true
    scope: user
    state: started
#    daemon_reload: true

