---
# ========== Audio ==========

- name: Agregar usuario alex a grupo audio
  ansible.builtin.user:
    name: alex
    groups: audio
    append: yes
  tags: [multimedia, audio, config]

- name: Configurar límites de audio en tiempo real
  ansible.builtin.copy:
    dest: /etc/security/limits.d/audio.conf
    content: |
      @audio   -  rtprio     95
      @audio   -  memlock    unlimited
      @audio   -  nice      -19
    owner: root
    group: root
    mode: '0644'
  tags: [multimedia, audio, config]

- name: Habilitar y arrancar rtkit-daemon
  ansible.builtin.systemd:
    name: rtkit-daemon
    enabled: true
    state: started
  tags: [multimedia, audio, service]

# ========== MPD ==========

- name: Agregar el usuario mpd al grupo del usuario alex
  user:
    name: mpd
    groups: alex
    append: true

- name: Agregar usuario mpd al grupo audio
  user:
    name: mpd
    groups: audio
    append: true

- name: Deshabilitar y enmascarar mpd.service del sistema
  systemd:
    name: mpd.service
    enabled: false
    masked: true
    state: stopped

- name: Deshabilitar y enmascarar mpd.socket del sistema
  systemd:
    name: mpd.socket
    enabled: false
    masked: true
    state: stopped

- name: Habilitar linger para alex
  command: loginctl enable-linger alex
