---
# ========== rtkit ==========
- name: Agregar usuario a grupo audio
  ansible.builtin.user:
    name: "{{ target_user }}"
    groups: audio
    append: yes
  tags: [multimedia, audio, config]

- name: Configurar límites de audio en tiempo real
  ansible.builtin.copy:
    dest: /etc/security/limits.d/audio.conf
    content: |
      @audio   -  rtprio     95
      @audio   -  memlock    unlimited
      @audio   -  nice      -19
    owner: root
    group: root
    mode: '0644'
  tags: [multimedia, audio, config]

- name: Habilitar y arrancar rtkit-daemon
  ansible.builtin.systemd:
    name: rtkit-daemon
    enabled: true
    state: started
  tags: [multimedia, audio, service]

