---
# ========== MPD ==========

- name: Agregar el usuario mpd al grupo del usuario
  user:
    name: mpd
    groups: "{{ target_user }}"
    append: true

- name: Agregar usuario mpd al grupo audio
  user:
    name: mpd
    groups: audio
    append: true

- name: Deshabilitar y enmascarar mpd.service del sistema
  systemd:
    name: mpd.service
    enabled: false
    masked: true
    state: stopped

- name: Deshabilitar y enmascarar mpd.socket del sistema
  systemd:
    name: mpd.socket
    enabled: false
    masked: true
    state: stopped

- name: Habilitar linger para user
  command: loginctl enable-linger "{{ target_user }}"
