---
# ========== MPD ==========

- name: Establecer permisos de directorio home
  file:
    path: "/home/{{ target_user }}"
    mode: '0710'

- name: Crear directorio ~/.mpd/playlists
  file:
    path: "/home/{{ target_user }}/.mpd/playlists"
    state: directory
    mode: '0777'

- name: Copiar configuración de MPD para usuario
  copy:
    src: "mpd.conf"
    dest: "/home/{{ target_user }}/.mpd/mpd.conf"
    mode: '0644'

- name: Habilitar servicio mpd para el user (systemd user)
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_uid }}"
  systemd:
    name: mpd.service
    scope: user
    enabled: true
    state: started
    daemon_reload: true
