---
- name: Clonar Ly desde Codeberg
  ansible.builtin.git:
    repo: "https://codeberg.org/fairyglade/ly.git"
    dest: /usr/local/src/ly
    version: "master"
    update: yes

- name: Compilar Ly con Zig
  ansible.builtin.command: /usr/local/zig/zig build
  args:
    chdir: /usr/local/src/ly
  register: ly_build
  changed_when: "'Built executable' in ly_build.stdout"

- name: Instalar Ly en el sistema
  ansible.builtin.command: /usr/local/zig/zig build installexe -Dinit_system=systemd
  args:
    chdir: /usr/local/src/ly
  register: ly_install
  changed_when: "'Installed executable' in ly_install.stdout"

- name: Habilitar Ly service
  ansible.builtin.systemd:
    name: ly.service
    enabled: yes
    state: started

- name: Configurar PAM de Ly (similar a Debian 12)
  ansible.builtin.copy:
    dest: /etc/pam.d/ly
    content: |
      auth       include      login
      -auth      optional     pam_gnome_keyring.so
      -auth      optional     pam_kwallet5.so

      account    include      login

      password   include      login
      -password  optional     pam_gnome_keyring.so use_authtok

      -session   optional     pam_systemd.so       class=greeter
      -session   optional     pam_elogind.so
      session    include      login
      -session   optional     pam_gnome_keyring.so auto_start
      -session   optional     pam_kwallet5.so      auto_start
    mode: '0644'

- name: Deshabilitar getty@tty2 (liberar TTY2)
  ansible.builtin.systemd:
    name: getty@tty2.service
    enabled: no
    state: stopped

- name: Reiniciar Ly service
  ansible.builtin.systemd:
    name: ly.service
    state: restarted
