# roles/desktop/tasks/install_common.yml
---

# Paquetes para desktop
- name: Instalar entorno de escritorio y gestor de ventanas
  apt:
    name: "{{ desktop_packages }}"
    state: present
    update_cache: yes

# Dependencias para Polybar
- name: Instalar dependencias de compilación para polybar
  apt:
    name: "{{ polybar_dependencies }}"
    state: present

# Dependencias para Picom
- name: Instalar dependencias de compilación para picom
  apt:
    name: "{{ picom_dependencies }}"
    state: present

- name: Eliminar LightDM y sus greeters
  ansible.builtin.apt:
    name:
      - lightdm
      - lightdm-gtk-greeter
      - liblightdm-gobject-1-0
      - liblightdm-gobject-dev
    state: absent
    purge: yes

# Instalación de Polybar
- name: Clonar repositorio de polybar
  git:
    repo: https://github.com/polybar/polybar
    dest: "{{ polybar_dir }}"
    recursive: yes
    update: no

- name: Compilar e instalar polybar
  shell: |
    mkdir -p build
    cd build
    cmake ..
    make -j$(nproc)
    make install
  args:
    chdir: "{{ polybar_dir }}"
    creates: "/usr/local/bin/polybar"
  when: polybar_dir is defined

# Instalación de Picom
- name: Clonar repositorio de picom
  git:
    repo: https://github.com/ibhagwan/picom.git
    dest: "{{ picom_dir }}"
    recursive: yes
    update: no

- name: Actualizar submódulos de picom
  command: git submodule update --init --recursive
  args:
    chdir: "{{ picom_dir }}"

- name: Compilar e instalar picom
  shell: |
    meson --buildtype=release . build
    ninja -C build
    ninja -C build install
  args:
    chdir: "{{ picom_dir }}"
    creates: "/usr/local/bin/picom"
  when: picom_dir is defined
