---
# ========== Dependencias para Polybar ==========

- name: Instalar dependencias de compilación para polybar
  apt:
    name: "{{ polybar_dependencies }}"
    state: present

# ========== Instalación de Polybar ==========

- name: Clonar repositorio de polybar
  git:
    repo: https://github.com/polybar/polybar
    dest: "{{ polybar_dir }}"
    recursive: yes
    update: no

- name: Compilar e instalar polybar
  shell: |
    mkdir -p build
    cd build
    cmake ..
    make -j$(nproc)
    make install
  args:
    chdir: "{{ polybar_dir }}"
    creates: "/usr/local/bin/polybar"
  when: polybar_dir is defined
