---

# ========== Instalar swaync ==========

- name: Instalar sway-notification-center
  apt:
    name: sway-notification-center
    state: present
    update_cache: yes

# ========== Enmascarar serviciod systemd-user ========== 

# (Debian NO lo soporta en sway)
- name: Enmascarar swaync.service para el usuario {{ target_user }}
  file:
    path: "/home/{{ target_user }}/.config/systemd/user/swaync.service"
    state: link
    src: "/dev/null"
  become: true
  become_user: "{{ target_user }}"

- name: Enmascarar dunst.service para el usuario {{ target_user }}
  file:
    path: "/home/{{ target_user }}/.config/systemd/user/dunst.service"
    state: link
    src: "/dev/null"
  become: true
  become_user: "{{ target_user }}"

# ==========  Reemplazar el icono del sistema mpd.svg ========== 
# (mpDris2-rs usa icon-path absoluto → SE DEBE reemplazar)

- name: Respaldar icono mpd.svg si existe
  shell: |
    if [ -f "{{ icono_mpd_destino }}" ]; then
      mv "{{ icono_mpd_destino }}" "{{ icono_mpd_destino }}.bak"
    fi
  args:
    executable: /bin/bash

- name: Copiar icono mpd personalizado
  copy:
    src: "{{ icono_mpd_origen }}"
    dest: "{{ icono_mpd_destino }}"
    mode: 0644

- name: Actualizar caché de iconos hicolor
  command: gtk-update-icon-cache /usr/share/icons/hicolor


