---
# ========== Instalación de paquetes ==========

# Paquetes base para desktop
- import_tasks: install_desktop_packages.yml
  become: true
  tags: [desktop, install, base]

# Dependencias de wayland
- import_tasks: install_wayland_dependencies.yml
  become: true
  tags: [desktop, install, wayland]

# Mako
- import_tasks: install_mako.yml
  become: true
  tags: [desktop, install, mako]

# Swaync
#- import_tasks: install_swaync.yml
#  become: true
#  tags: [desktop, install, swaync]

# Rofi
- import_tasks: install_rofi.yml
  become: true
  tags: [desktop, rofi]

# Gestor de login
- import_tasks: install_ly.yml
  become: true
  tags: [desktop, ly]

# ========== Configuración de sistema ==========

# ========== Configuración root ==========

# ========== Configuración usuario ==========
