---
# ========== Configuración básica de sway ==========

- name: Crear directorio de configuración de Sway para usuario alex
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config/sway"
    state: directory
    mode: '0755'

- name: Copiar configuración básica de Sway para usuario alex
  ansible.builtin.copy:
    src: /etc/sway/config
    dest: /home/{{ target_user }}/.config/sway/config
    mode: '0644'
