---

# *** WALLPAPERS (alex) ***

- name: Crear carpeta ~/Wallpaper
  file:
    path: ~/Wallpaper
    state: directory
    mode: '0755'

- name: Verificar que el directorio de wallpapers existe
  stat:
    path: "{{ wallpapers }}"
  register: wallpapers_home_dir_stat

- name: Copiar wallpapers a ~/Wallpaper solo si existe el directorio
  copy:
    src: "{{ item }}"
    dest: ~/Wallpaper/
  with_fileglob:
    - "{{ wallpapers }}/*"
  when: wallpapers_home_dir_stat.stat.exists

# *** FUENTES EN ~/.local/share/fonts ***

- name: Crear carpeta ~/.local/share/fonts si no existe
  file:
    path: ~/.local/share/fonts
    state: directory
    mode: '0755'

- name: Verificar que el directorio de fuentes personales existe
  stat:
    path: "{{ fonts_home }}"
  register: fonts_home_dir_stat

- name: Copiar fuentes personales en ~/.local/share/fonts solo si el origen existe
  copy:
    src: "{{ fonts_home }}/"
    dest: ~/.local/share/fonts/
    mode: '0644'
    recursive: true
  when: fonts_home_dir_stat.stat.exists
  register: fonts_home_copy_result

- name: Recargar caché de fuentes sólo si se copiaron nuevas
  command: fc-cache -fv
  args:
    warn: false
  when: fonts_home_copy_result is changed

# *** PERSONALIZAR lxappearance ***

- name: Extraer y mover tema Dracula (lxappearance)
  unarchive:
    src: "{{ lxappearance_themes_zip }}"
    dest: ~/.themes/
    remote_src: false

- name: Renombrar carpeta gtk-master a dracula
  command: mv ~/.themes/gtk-master ~/.themes/dracula
  args:
    creates: ~/.themes/dracula

- name: Extraer y mover iconos y cursores Dracula (extrae todo tipo .zip y .tar)
  unarchive:
    src: "{{ item }}"
    dest: ~/.icons/
    remote_src: false
  with_fileglob:
    - "{{ lxappearance_icons }}/*.zip"
    - "{{ lxappearance_icons }}/*.tar"



