---
common_env_packages:
  - build-essential
  - cargo
  - automake
  - cmake
  - meson
  - ninja-build
  - pkg-config
  - pkgconf
  - git
  - libpam0g-dev
  - golang
  - vim
  - libasound2-dev

common_extra_packages:
  - brightnessctl
  - imagemagick
  - rsync
  - acpi
  - grim
  - slurp
  - wl-clipboard
  - swappy
  - xwayland
  - acl
