---
common_env_packages:
  - build-essential
  - libpam0g-dev
  - git
  - vim
  - xcb
  - libxcb-util0-dev
  - libxcb-ewmh-dev
  - libxcb-randr0-dev
  - libxcb-icccm4-dev
  - libxcb-keysyms1-dev
  - libxcb-xinerama0-dev
  - libasound2-dev
  - libxcb-xtest0-dev
  - libxcb-shape0-dev

common_extra_packages:
  - scrot
  - scrub
  - zsh
  - xclip
  - bat
  - locate
  - neofetch
  - wmname
  - acpi
  - xorg
  - brightnessctl
  - imagemagick
  - ranger
  - kitty
