---
common_env_packages:
  - build-essential
  - automake
  - cmake
  - meson
  - ninja-build
  - pkg-config
  - pkgconf
  - git
  - libpam0g-dev
  - golang
  - vim
  - libasound2-dev
  - libssl-dev
  - curl
  - autoconf
  - autopoint
  - libtool
  - clang
  - yasm
  - intltool
  - pkg-config
  - libjansson-dev
  - libblocksruntime-dev

common_extra_packages:
  - brightnessctl
  - imagemagick
  - rsync
  - acpi
  - grim
  - slurp
  - wl-clipboard
  - swappy
  - xwayland
  - acl
