---
- name: Actualizar el sistema
  apt:
    update_cache: yes
    upgrade: dist

- name: Instalar dependencias de entorno
  apt:
    name: "{{ common_env_packages }}"
    state: present
    update_cache: yes

- name: Instalar paquetes adicionales
  apt:
    name: "{{ common_extra_packages }}"
    state: present
    update_cache: yes
