---
# Instalación de Cloudflare WARP en Debian

- name: Asegurar que dependencias básicas estén instaladas y privoxy
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - lsb-release
    state: present
    update_cache: yes

- name: Crear directorio para keyrings si no existe
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Descargar y desproteger la llave GPG de Cloudflare
  ansible.builtin.shell:
    cmd: "curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg"
    creates: /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

- name: Añadir el repositorio de Cloudflare
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main"
    filename: cloudflare-client
    state: present

- name: Instalar el paquete cloudflare-warp
  ansible.builtin.apt:
    name: cloudflare-warp
    state: present
    update_cache: yes

- name: Asegurar que el servicio de WARP esté corriendo
  ansible.builtin.systemd:
    name: warp-svc
    state: started
    enabled: yes
