---
- name: Renombrar .config si existe
  ansible.builtin.shell: |
    if [ -d "/home/{{ target_user }}/.config" ]; then
      mv "/home/{{ target_user }}/.config" "/home/{{ target_user }}/.config.bak_$(date +%Y%m%d%H%M%S)"
    fi

- name: Crear carpeta ~/bin si no existe
  ansible.builtin.file:
    path: "/home/{{ target_user }}/bin"
    state: directory
    mode: '0755'

- name: Instalar chezmoi en ~/bin
  ansible.builtin.shell: |
    sh -c "$(wget -qO- get.chezmoi.io)" -- -b /home/{{ target_user }}/bin
  args:
    creates: "/home/{{ target_user }}/bin/chezmoi"

- name: Verificar si chezmoi está instalado
  ansible.builtin.stat:
    path: "/home/{{ target_user }}/bin/chezmoi"
  register: chezmoi_stat

- name: Verificar versión de chezmoi
  ansible.builtin.command: "/home/{{ target_user }}/bin/chezmoi --version"
  register: chezmoi_version
  when: chezmoi_stat.stat.exists

- debug:
    var: chezmoi_version.stdout
  when: chezmoi_stat.stat.exists

- name: Inicializar chezmoi con tu repo
  ansible.builtin.command: "/home/{{ target_user }}/bin/chezmoi init Navarro76/BSPWMvampire.git"
  args:
    creates: "/home/{{ target_user }}/.local/share/chezmoi"

#- name: Mostrar diff de chezmoi (opcional)
#  ansible.builtin.command: "/home/{{ target_user }}/bin/chezmoi diff"
#  register: chezmoi_diff
#  changed_when: false

#- debug:
#    var: chezmoi_diff.stdout

#- name: Aplicar dotfiles
#  ansible.builtin.command: "/home/{{ target_user }}/bin/chezmoi apply -v"

- name: Aplicar dotfiles de chezmoi de forma segura
  ansible.builtin.shell: "/home/{{ target_user }}/bin/chezmoi apply -v"
  register: chezmoi_apply
  changed_when: true
  ignore_errors: false

- debug:
    msg: "{{ chezmoi_apply.stdout_lines[:20] }}"
