---
# Ruta base para clonar repos desde GitHub
github_dir: "/home/{{ ansible_user_id }}/github"

# Directorios específicos para proyectos

# Rutas a iconos mpd
icono_mpd_origen: "{{ role_path }}/files/mpd.svg"
icono_mpd_destino: "/usr/share/icons/hicolor/scalable/apps/mpd.svg"

# Directorio estándar para programas compilados manualmente
install_prefix: "/usr/local"

desktop_packages:
  - sway
  - swaybg
  - swaylock
  - swayidle
  - swayimg
  - papersway
  - waybar
  - cava
  - gammastep
  - jq
  - waybar
  - libnotify-bin
  - nwg-look
  - qt5ct
  - qt6ct
  - qt6-wayland
  - hardinfo2

wayland_dependencies:
  - wayland-protocols
  - libwayland-dev
  - libpango1.0-dev

desktop_apps:
  - pcmanfm
  - gvfs
  - gvfs-backends
  - mate-polkit
