---
# Ruta base para clonar repos desde GitHub
github_dir: "/home/{{ ansible_user_id }}/github"

# Directorios específicos para proyectos

# Ruta al archivo .deb de web-greeter (este está dentro del rol)
web_greeter_deb_path: "{{ role_path }}/files/web-greeter-3.5.3-debian.deb"

desktop_packages:
  - sway
  - swaybg
  - swaylock
  - swayidle
  - mako-notifier
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - swayimg
  - papersway
  - waybar
  - gammastep

rofi_dependencies:
  - build-essential
  - git
  - meson
  - ninja-build
  - pkg-config

wayland_dependencies:
  - wayland-protocols
  - libwayland-dev
  - libpango1.0-dev
