---

- name: Ensure build dependencies are installed
  apt:
    name:
      - libinih-dev
      - libgbm-dev
      - libdrm-dev
    state: present
    update_cache: yes

- name: Clone xdg-desktop-portal-wlr repo
  git:
    repo: "https://github.com/emersion/xdg-desktop-portal-wlr.git"
    dest: "/opt/xdg-desktop-portal-wlr"
    version: master
    force: no
  register: wlr_repo

- name: Configure build directory
  command: meson setup build --prefix=/usr/local
  args:
    chdir: "/opt/xdg-desktop-portal-wlr"
  when: wlr_repo.changed
  register: meson_setup

- name: Compile xdg-desktop-portal-wlr
  command: ninja -C build
  args:
    chdir: "/opt/xdg-desktop-portal-wlr"
  when: meson_setup.changed
  register: ninja_build

- name: Install compiled version to /usr/local
  command: ninja -C build install
  args:
    chdir: "/opt/xdg-desktop-portal-wlr"
  when: ninja_build.changed
