---

flatpak_packages:
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk

# Flatpak runtimes a instalar para el usuario
flatpak_runtimes:
  - org.freedesktop.Platform//23.08

# Flatpak apps a instalar para el usuario
flatpak_apps:
  - com.github.marktext.marktext
  - org.gnome.Loupe
  - com.zettlr.Zettlr
  - md.obsidian.Obsidian
#  - org.onlyoffice.desktopeditors
  - org.librepcb.LibrePCB

flatpak_ebookreader:
#  - com.calibre_ebook.calibre
#  - net.sourceforge.mcomix
  - info.febvre.Komikku
  - com.yacreader.YACReader

flatpak_games:
  - net.lutris.Lutris
#  - com.usebottles.bottles
#  - org.libretro.RetroArch
#  - com.dosbox_x.DOSBox-X
#  - io.github.dosbox-staging
#  - net.pcsx2.PCSX2
#  - net.rpcs3.RPCS3

flatpak_download:
  - org.freedownloadmanager.Manager

flatpak_network:
  - io.gitlab.librewolf-community

flatpak_audio:
  - me.timschneeberger.jdsp4linux

flatpak_audio_recording:
  - org.ardour.Ardour
  - org.zrythm.Zrythm
#  - com.ntrack.n-track
#  - com.bitwig.BitwigStudio

flatpak_plugins_audio:
  - org.freedesktop.LinuxAudio.Plugins.Calf
  - org.freedesktop.LinuxAudio.Plugins.Surge-XT
  - org.freedesktop.LinuxAudio.Plugins.Cardinal
  - org.freedesktop.LinuxAudio.Plugins.Yoshimi
  - org.freedesktop.LinuxAudio.Plugins.guitarixvst

# Controla si se actualizan las apps del usuario automáticamente
flatpak_update: true

# Permisos adicionales del sandbox:
#  - "--filesystem=home com.visualstudio.code"
#  - "--filesystem=xdg-download com.spotify.Client"
#  - "--socket=system-bus com.example.App"

flatpak_overrides:
  - app: "net.lutris.Lutris"
    permissions: "--filesystem=/media:ro --filesystem=/run/media:ro --socket=x11"

# aplicaciones con problemas con Wayland/WLroots
#  - com.github.johnfactotum.Foliate (funiconó, pero instalé con apt
#  - com.yacreader.YACReader
#  - org.qownnotes.QOwnNotes
#  - io.github.htkhiem.Euphonica

# apliaciones desinstaladas por otras razones
#  - net.cozic.joplin_desktop
#  - org.gnome.EasyTAG



