---

# *** WALLPAPERS (alex) ***

- name: Crear carpeta ~/Wallpaper
  file:
    path: ~/Wallpaper
    state: directory
    mode: '0755'

- name: Verificar que el directorio de wallpapers existe
  stat:
    path: "{{ wallpapers }}"
  register: wallpapers_home_dir_stat

- name: Copiar wallpapers a ~/Wallpaper solo si existe el directorio
  copy:
    src: "{{ item }}"
    dest: ~/Wallpaper/
  with_fileglob:
    - "{{ wallpapers }}/*"
  when: wallpapers_home_dir_stat.stat.exists


# *** PERSONALIZAR lxappearance ***

- name: Crear directorio ~/.themes si no existe
  ansible.builtin.file:
    path: /home/alex/.themes
    state: directory
    mode: '0755'

- name: Extraer y mover tema Dracula (lxappearance)
  unarchive:
    src: "{{ lxappearance_themes_zip }}"
    dest: ~/.themes/
    remote_src: false

- name: Renombrar carpeta gtk-master a dracula
  command: mv ~/.themes/gtk-master ~/.themes/dracula
  args:
    creates: ~/.themes/dracula

- name: Crear directorio ~/.icons si no existe
  ansible.builtin.file:
    path: ~/.icons
    state: directory
    mode: '0755'

- name: Extraer y mover iconos y cursores Dracula (extrae todo tipo .zip y .tar)
  unarchive:
    src: "{{ item }}"
    dest: ~/.icons/
    remote_src: false
  with_fileglob:
    - "{{ lxappearance_icons }}/*.zip"
    - "{{ lxappearance_icons }}/*.tar.xz"
