---
# *** FUENTES ***

- name: Verificar que el directorio de fuentes OpenType existe
  stat:
    path: "{{ fonts_opentype }}"
  register: opentype_dir_stat

- name: Copiar fuentes OpenType si existe el directorio
  ansible.posix.synchronize:
    src: "{{ fonts_opentype }}/"
    dest: /usr/share/fonts/opentype/
    archive: true
    recursive: true
    delete: false
  when: opentype_dir_stat.stat.exists
  register: opentype_fonts_copy_result

- name: Ajustar permisos de las fuentes
  ansible.builtin.file:
    path: /usr/share/fonts/opentype
    recurse: yes
    owner: root
    group: root
    mode: '0644'
    
- name: Verificar que el directorio de fuentes TrueType existe
  stat:
    path: "{{ fonts_truetype }}"
  register: truetype_dir_stat

- name: Copiar fuentes TrueType en /usr/share/fonts/truetype
  ansible.posix.synchronize:
    src: "{{ fonts_truetype }}/"
    dest: /usr/share/fonts/truetype/
    archive: true
    recursive: true
    delete: false
  when: truetype_dir_stat.stat.exists
  register: truetype_fonts_copy_result

- name: Ajustar permisos de las fuentes
  ansible.builtin.file:
    path: /usr/share/fonts/truetype
    recurse: yes
    owner: root
    group: root
    mode: '0644'

- name: Recargar caché de fuentes sólo si se copiaron nuevas
  ansible.builtin.command: fc-cache -f -v
  when: >
    opentype_fonts_copy_result is changed or
    truetype_fonts_copy_result is changed

# *** WEB-GREETER ***

- name: Asegurar que existe /usr/share/web-greeter/themes/
  file:
    path: /usr/share/web-greeter/themes/
    state: directory
    mode: '0755'

- name: Verificar que el directorio de themes para web-greeter existe
  stat:
    path: "{{ web_greeter_themes }}"
  register: web_greeter_themes_dir_stat

- name: Copiar temas de web-greeter (dracula, gruvbox y simple) al sistema
  ansible.posix.synchronize:
    src: "{{ web_greeter_themes }}/"
    dest: /usr/share/web-greeter/themes/
    archive: true
    recursive: true
    delete: false
  when: web_greeter_themes_dir_stat.stat.exists

- name: Ajustar permisos a los temas de web-greeter 
  ansible.builtin.file:
    path: /usr/share/web-greeter/themes
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Verificar que el archivo de configuración de web-greeter existe
  stat:
    path: "{{ web_greeter_config }}"
  register: web_greeter_config_stat

- name: Copiar archivo de configuración de web-greeter
  copy:
    src: "{{ web_greeter_config }}"
    dest: /etc/lightdm/web-greeter.yml
    mode: '0644'
  when: web_greeter_config_stat.stat.exists

# *** GRUB ***

- name: Verificar que el directorio de temas de grub existe
  stat:
    path: "{{ grub_theme_dir }}"
  register: grub_theme_dir_stat

- name: Copiar tema dracula para grub
  ansible.posix.synchronize:
    src: "{{ grub_theme_dir }}"
    dest: /boot/grub/themes/
    archive: true
    recursive: true
    delete: false
  when: grub_theme_dir_stat.stat.exists

- name: Ajustar permisos a los temas de grub
  ansible.builtin.file:
    path: /boot/grub/themes
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Verificar que el archivo de configuración de grub existe
  stat:
    path: "{{ grub_config }}"
  register: grub_config_stat

- name: Copiar archivo de configuración de grub
  copy:
    src: "{{ grub_config }}"
    dest: /etc/default/grub
    mode: '0644'
    remote_src: false
  when: grub_config_stat.stat.exists

- name: Regenerar configuración grub
  command: grub-mkconfig -o /boot/grub/grub.cfg