---
# *** FUENTES ***

- name: Verificar que el directorio de fuentes OpenType existe
  stat:
    path: "{{ fonts_opentype }}"
  register: opentype_dir_stat

- name: Copiar fuentes OpenType si existe el directorio
  ansible.posix.synchronize:
    src: "{{ fonts_opentype }}/"
    dest: /usr/share/fonts/opentype/
    archive: true
    recursive: true
    delete: false
  when: opentype_dir_stat.stat.exists
  register: opentype_fonts_copy_result

- name: Verificar que el directorio de fuentes TrueType existe
  stat:
    path: "{{ fonts_truetype }}"
  register: truetype_dir_stat

- name: Copiar fuentes TrueType en /usr/share/fonts/truetype
  ansible.posix.synchronize:
    src: "{{ fonts_truetype }}/"
    dest: /usr/share/fonts/truetype/
    archive: true
    recursive: true
    delete: false
  when: truetype_dir_stat.stat.exists
  register: truetype_fonts_copy_result

- set_fact:
    font_dirs:
      - /usr/share/fonts/truetype
      - /usr/share/fonts/opentype

- name: Ajustar permisos de directorios de fuentes
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ font_dirs }}"

- name: Encontrar archivos de fuentes
  ansible.builtin.find:
    paths: "{{ item }}"
    recurse: yes
    file_type: file
  loop: "{{ font_dirs }}"
  register: fonts_files

- name: Aplicar permisos 644 a archivos de fuentes
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ fonts_files.results | map(attribute='files') | flatten }}"

- name: Recargar caché de fuentes sólo si se copiaron nuevas
  ansible.builtin.command: fc-cache -f -v
  when: >
    opentype_fonts_copy_result is changed or
    truetype_fonts_copy_result is changed

# *** GRUB ***

- name: Verificar que el directorio de temas de grub existe
  stat:
    path: "{{ grub_theme_dir }}"
  register: grub_theme_dir_stat

- name: Copiar tema dracula para grub
  ansible.posix.synchronize:
    src: "{{ grub_theme_dir }}"
    dest: /boot/grub/themes/
    archive: true
    recursive: true
    delete: false
  when: grub_theme_dir_stat.stat.exists

- name: Ajustar permisos a los temas de grub
  ansible.builtin.file:
    path: /boot/grub/themes
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Verificar que el archivo de configuración de grub existe
  stat:
    path: "{{ grub_config }}"
  register: grub_config_stat

- name: Copiar archivo de configuración de grub
  copy:
    src: "{{ grub_config }}"
    dest: /etc/default/grub
    mode: '0644'
    remote_src: false
  when: grub_config_stat.stat.exists

- name: Regenerar configuración grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
