---
# ========== Skins Midnight Commander ==========

- name: Verificar que el directorio de skins de mc existe
  stat:
    path: "{{ mc_skins }}"
  register: mc_skins_dir_stat

- name: Copiar skins de mc
  copy:
    src: "{{ item }}"
    dest: /usr/share/mc/skins/
    mode: '0644'
  with_fileglob:
    - "{{ mc_skins }}/*.ini"
  when: mc_skins_dir_stat.stat.exists

