---
#========== Wallpapers (user) ========== 

- name: Crear carpeta ~/Wallpaper
  become_user: "{{ target_user }}"
  file:
    path: "/home/{{ target_user }}/Wallpaper"
    state: directory
    mode: '0755'

- name: Verificar que el directorio de wallpapers existe
  stat:
    path: "{{ wallpapers }}"
  register: wallpapers_home_dir_stat

- name: Copiar wallpapers a ~/Wallpaper solo si existe el directorio
  become_user: "{{ target_user }}"
  copy:
    src: "{{ item }}"
    dest: "/home/{{ target_user }}/Wallpaper/"
  with_fileglob:
    - "{{ wallpapers }}/*"
  when: wallpapers_home_dir_stat.stat.exists

