---
# Powerlevel10k
- name: Clonar powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.powerlevel10k
    depth: 1

# Cambiar shell a ZSH
- name: Cambiar shell a ZSH para alex
  user:
    name: alex
    shell: /usr/bin/zsh
  
- name: Cambiar shell a ZSH para root
  user:
    name: root
    shell: /usr/bin/zsh

# ZSH config
- name: Eliminar .zshrc existente
  file:
    path: ~/.zshrc
    state: absent

- name: Enlazar .zshrc de alex
  file:
    src: /home/alex/.zshrc
    dest: ~/.zshrc
    state: link
    force: true

# Neovim
- name: Crear carpetas de configuración de Neovim
  file:
    path: ~/.config/nvim
    state: directory
    recurse: yes

- name: Copiar init.lua
  copy:
    src: "{{ neovim_config }}"
    dest: ~/.config/nvim/init.lua
    mode: '0644'

# Oh My Tmux
- name: Clonar Oh My Tmux
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: ~/.tmux
    depth: 1

- name: Enlazar .tmux.conf
  file:
    src: ~/.tmux/.tmux.conf
    dest: ~/.tmux.conf
    state: link
    force: true

- name: Copiar tmux.conf.local
  copy:
    src: "{{ tmux_config_local }}"
    dest: ~/.tmux.conf.local
    mode: '0644'

# Tema Dracula
- name: Clonar Dracula OMT
  git:
    repo: https://github.com/atgmello/dracula.omt.git
    dest: ~/dracula.omt
    depth: 1

- name: Crear carpeta de temas Dracula
  file:
    path: ~/.config/oh-my-tmux/themes
    state: directory
    recurse: true

- name: Enlazar dracula.conf
  file:
    src: ~/dracula.omt/dracula.conf
    dest: ~/.config/oh-my-tmux/themes/dracula.conf
    state: link
    force: true

# Reiniciar servidor de tmux
- name: Reiniciar servidor de tmux
  shell: tmux kill-server || true
  become: false
  tags: [optional]
