---
# Instalación de paquetes deb
- name: Instalar lsd desde .deb
  apt:
    deb: "{{ lsd_deb }}"
  when: not ansible_check_mode

- name: Instalar bat desde .deb
  apt:
    deb: "{{ bat_deb }}"
  when: not ansible_check_mode

