---
# Neovim (AppImage)
- name: Dar permisos a AppImage de Neovim
  file:
    path: "{{ neovim_appimage }}"
    mode: '0755'

- name: Copiar Neovim AppImage a /usr/local/bin
  copy:
    src: "{{ neovim_appimage }}"
    dest: /usr/local/bin/nvim
    mode: '0755'

