---
# Plugins ZSH (apt + zsh-sudo)
- name: Instalar plugins de ZSH
  apt:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present

- name: Crear carpeta zsh-sudo
  file:
    path: /usr/share/zsh-sudo
    state: directory

- name: Copiar plugin zsh-sudo
  copy:
    src: "{{ zsh_sudo_plugin }}"
    dest: /usr/share/zsh-sudo/sudo.plugin.zsh
    mode: '0644'

