---
# ========== Paquetes base ==========

- import_tasks: install_terminal_packages.yml
  become: true
  tags: [terminal, install, packages]

- import_tasks: install_terminal_deb.yml
  become: true
  tags: [terminal, install, deb]

- import_tasks: install_neovim.yml
  become: true
  tags: [terminal, install, neovim]

- import_tasks: install_zsh_plugins.yml
  become: true
  tags: [terminal, install, zsh]

# ========== Configuración de root ==========

- import_tasks: root_zsh_shell.yml
  become: true
  become_user: root
  tags: [terminal, root, zsh]

- import_tasks: root_zshrc_symlink.yml
  become: true
  become_user: root
  tags: [terminal, root, zshrc]

- import_tasks: root_neovim.yml
  become: true
  become_user: root
  tags: [terminal, root, neovim]

#- import_tasks: root_powerlevel10k.yml
#  become: true
#  become_user: root
#  tags: [terminal, root, p10k]

- import_tasks: root_ohmyposh.yml
  become: true
  become_user: root
  tags: [terminal, root, ohmyposh]

- import_tasks: root_ohmytmux.yml
  become: true
  become_user: root
  tags: [terminal, root, tmux]

# ========== Configuración de usuario ==========

- import_tasks: user_fzf.yml
  become: true
  become_user: "{{ target_user }}"
  tags: [terminal, user, fzf]

- import_tasks: user_neovim.yml
  become: true
  become_user: "{{ target_user }}"
  tags: [terminal, user, neovim]

#- import_tasks: user_powerlevel10k.yml
#  become: true
#  become_user: "{{ target_user }}"
#  tags: [terminal, user, p10k]

- import_tasks: user_ohmyposh_themes.yml
  become: true
  become_user: "{{ target_user }}"
  tags: [terminal, user, ohmyposh_themes]

- import_tasks: user_ohmytmux.yml
  become: true
  become_user: "{{ target_user }}"
  tags: [terminal, user, tmux]

# ========== Configuración de sistema ==========
