---
# Powerlevel10k
- name: Clonar powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/root/.powerlevel10k"
    depth: 1

- name: Copiar p10k.zsh para root
  copy:
    src: "{{ p10k_config }}"
    dest: "/root/.p10k.zsh"
    mode: '0644'
