---
# ========== Oh My Posh ==========

- name: Descargar Oh My Posh
  ansible.builtin.get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
    dest: /usr/local/bin/oh-my-posh
    mode: '0755'
  register: download_oh_my_posh
