---
# Oh My Tmux (user)
- name: Clonar Oh My Tmux (user)
  git:
    repo: https://github.com/gpakosz/.tmux.git
    dest: "/home/{{ target_user }}/.tmux"
    depth: 1

- name: Enlazar .tmux.conf (user)
  file:
    src: "/home/{{ target_user }}/.tmux/.tmux.conf"
    dest: "/home/{{ target_user }}/.tmux.conf"
    state: link
    force: true

- name: Copiar tmux.conf.local para user
  copy:
    src: "{{ tmux_config_local }}"
    dest: "/home/{{ target_user }}/.tmux.conf.local"

# Tema Dracula para Oh My Tmux (user)
- name: Clonar Dracula OMT para user
  git:
    repo: https://github.com/atgmello/dracula.omt.git
    dest: "/home/{{ target_user }}/dracula.omt"
    depth: 1

- name: Crear carpeta de temas Dracula (user)
  file:
    path: "/home/{{ target_user }}/.config/oh-my-tmux/themes"
    state: directory
    recurse: true

- name: Enlazar dracula.conf (user)
  file:
    src: "/home/{{ target_user }}/dracula.omt/dracula.conf"
    dest: "/home/{{ target_user }}/.config/oh-my-tmux/themes/dracula.conf"
    state: link
    force: true
