---
- name: Copiar whichSystem.py a /usr/local/bin/
  copy:
    src: "{{ hacker_whichSystem }}"
    dest: "/usr/local/bin/whichSystem.py"
    mode: '0755'

- name: Copiar screenshot a /usr/local/bin/
  copy:
    src: "{{ hacker_screenshot }}"
    dest: "/usr/local/bin/screenshot"
    mode: '0755'

- name: Asignar permisos a scripts específicos
  file:
    path: "{{ item }}"
    mode: '0755'
  loop:
    - "/usr/local/bin/whichSystem.py"
    - "/usr/local/bin/screenshot"

# ========== fastTCPScan ==========
- name: Copiar fastTCPScan.go a /usr/bin/
  copy:
    src: "{{ hacker_fastTCPScan }}"
    dest: "/usr/bin/fastTCPScan.go"
    mode: '0644'

- name: Compilar fastTCPScan.go
  command: go build -ldflags "-s -w" -o /usr/bin/fastTCPScan /usr/bin/fastTCPScan.go
  args:
    creates: /usr/bin/fastTCPScan

- name: Verificar si upx está disponible
  command: command -v upx
  register: upx_check
  ignore_errors: true
  changed_when: false

- name: Comprimir fastTCPScan con upx (si está disponible)
  command: upx --best /usr/bin/fastTCPScan
  when: upx_check.rc == 0
